image:
  - Visual Studio 2019
  
install:  
  - git submodule update --init --recursive --depth 1
      
build_script:
- cmd: cmake -H.\openssl-cmake -G "Visual Studio 16 2019" -A Win32 -B./build_x86 -DCMAKE_INSTALL_PREFIX=./package_x86 -DCMAKE_DEBUG_POSTFIX="d"
- cmd: cmake -H.\openssl-cmake -G "Visual Studio 16 2019" -A x64 -B./build_x64 -DCMAKE_INSTALL_PREFIX=./package_x64  -DCMAKE_DEBUG_POSTFIX="d"

build_script:
- cmd: cmake --build build_x86 --target INSTALL --config Debug
- cmd: cmake --build build_x64 --target INSTALL --config Debug
- cmd: cmake --build build_x86 --target INSTALL --config Release
- cmd: cmake --build build_x64 --target INSTALL --config Release

after_test:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: nuget pack -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production