image:
  - Visual Studio 2019
  
install:  
  - git submodule update --init --recursive
      
build_script:
- cmd: setlocal
- cmd: pushd openssl
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
- cmd: C:\Strawberry\perl\bin\perl.exe Configure VC-WIN32 no-asm --prefix=%APPVEYOR_BUILD_FOLDER%\repository --openssldir=%APPVEYOR_BUILD_FOLDER%\repository
- cmd: del *.lib *.dll *.exp *.pdb
- cmd: nmake clean
- cmd: nmake
- cmd: nmake install
- cmd: popd
- cmd: endlocal
  
after_test:
  - cmd: nuget pack -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production