image:
  - Visual Studio 2019
  
install:  
  - git submodule update --init --recursive
  
before_build:
- cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat"
- cmd: cd openssl
- cmd: C:\Strawberry\perl\bin\perl.exe Configure VC-WIN32 no-asm
    
build_script:
- cmd: nmake
  
after_test:
  - cmd: nuget pack -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production